spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Projects/h2/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true # sysout 으로 출력, 비권장
        format_sql: true # 쿼리문을 개행으로 이쁘게 출력하기
        highlight_sql: true # 쿼리명령어에 색을 부여
        use_sql_comment: true # SQL 내부에 주석을 추가?
#    open-in-view: false # Explicitly configure spring.jpa.open-in-view to disable this warning 끄기
  thymeleaf:
    # resources:templates/ + { ViewName } + .html
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org:
      hibernate:
        SQL: debug # log 로 출력, 권장
        type:
          descriptor:
            sql: trace # 파라미터에 바인딩되는 값을 표시
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
        orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
